passing_tap_sources = [
  'indexed_list_clean.c',
  'indexed_list_create_empty.c',
  'indexed_list_insert_back.c',
  'indexed_list_insert_even.c',
  'indexed_list_insert_front.c',
  'indexed_list_move_after.c',
  'indexed_list_remove_back_to_empty.c',
  'indexed_list_remove_front_to_empty.c',
  'indexed_list_remove_even.c',
  'indexed_list_selection_sort.c',
  'indexed_list_insertion_sort.c',
]

passing_return_sources = [
]
