passing_tap_sources = [
]

passing_return_sources = [
  'rb_tree_case1.c',
  'rb_tree_case2.c',
  'rb_tree_case3.c',
  'rb_tree_case4.c',
  'rb_tree_case5.c',
  'rb_tree_case6.c',
  'rb_tree_insert_found.c',
  'rb_tree_remove.c',
  'rb_tree_remove_case3.c',
  'rb_tree_remove_case5.c',
  'rb_tree_remove_case6.c',
  'rb_tree_remove_red.c',
  'rb_tree_remove_root.c',
  'rb_tree_remove_rs.c',
  'rb_tree_remove_ls.c',
]
