passing_tap_sources = [
]

passing_return_sources = [
  'bsearch_tree_create_empty.c',
  'bsearch_tree_find.c',
  'bsearch_tree_insert.c',
  'bsearch_tree_insert_found.c',
  'bsearch_tree_insert_root.c',
  'bsearch_tree_insert_remove_root.c',
  'bsearch_tree_max.c',
  'bsearch_tree_max_empty.c',
  'bsearch_tree_min.c',
  'bsearch_tree_min_empty.c',
  'bsearch_tree_remove.c',
  'bsearch_tree_remove_ls.c',
  'bsearch_tree_remove_rs.c',
  'bsearch_tree_remove_unexistent.c',
]
