passing_test_sources = [
  'linked_list_ref_append_back.c',
  'linked_list_ref_append_front.c',
  'linked_list_ref_clean.c',
  'linked_list_ref_create_empty.c',
  'linked_list_ref_find_equals.c',
  'linked_list_ref_find_in.c',
  'linked_list_ref_find_not_in.c',
  'linked_list_ref_from_tab.c',
  'linked_list_ref_insert_back.c',
  'linked_list_ref_insert_even.c',
  'linked_list_ref_insert_null.c',
  'linked_list_ref_no_free_element.c',
  'linked_list_ref_push_back.c',
  'linked_list_ref_push_front.c',
  'linked_list_ref_push_and_pop_back.c',
  'linked_list_ref_push_and_pop_front.c',
  'linked_list_ref_pop_back_to_empty.c',
  'linked_list_ref_pop_front_to_empty.c',
  'linked_list_ref_remove_back_to_empty.c',
  'linked_list_ref_remove_even.c',
  'linked_list_ref_remove_front_to_empty.c',
  'linked_list_ref_transform_square.c',
  'linked_list_ref_to_tab.c',
]
