#ifndef ERRORS_H
#define ERRORS_H

#define ERROR_ALLOCATION_FAILED 1

#define ERROR_INVALID_PARAM (1 << 3)
#define ERROR_INVALID_PARAM1 (ERROR_INVALID_PARAM | 1)
#define ERROR_INVALID_PARAM2 (ERROR_INVALID_PARAM | 2)
#define ERROR_INVALID_PARAM3 (ERROR_INVALID_PARAM | 3)
#define ERROR_INVALID_PARAM4 (ERROR_INVALID_PARAM | 4)
#define ERROR_INVALID_PARAM5 (ERROR_INVALID_PARAM | 5)
#define ERROR_INVALID_PARAM6 (ERROR_INVALID_PARAM | 6)
#define ERROR_INVALID_PARAM7 (ERROR_INVALID_PARAM | 7)

#define ERROR_GRAPH_FORMAT (2 << 3)
#define ERROR_GRAPH_HAS_NO_NODE (ERROR_GRAPH_FORMAT | 1)
#define ERROR_GRAPH_SHOULDBE_DAG (ERROR_GRAPH_FORMAT | 2)
#define ERROR_GRAPH_HAS_NEGATIVE_WEIGHTS (ERROR_GRAPH_FORMAT | 3)

#endif
