passing_tap_sources = [
]

passing_return_sources = [
  'avl_tree_find.c',
  'avl_tree_insert.c',
  'avl_tree_insert_balance.c',
  'avl_tree_insert_found.c',
  'avl_tree_insert_root.c',
  'avl_tree_insert_remove_root.c',
  'avl_tree_max.c',
  'avl_tree_min.c',
  'avl_tree_remove.c',
  'avl_tree_remove_ls.c',
  'avl_tree_remove_rs.c',
]
